# 微服务配置文件

# 服务配置
server:
  # 网关端口
  gateway_port: 8080
  # gRPC 端口
  grpc_port: 50051
  # 运行模式: debug, release, test
  mode: debug
  # 优雅关闭超时时间（秒）
  shutdown_timeout: 30

# 数据库配置
database:
  host: localhost
  port: 5432
  user: postgres
  password: your_password
  dbname: microservice
  # 连接池配置
  max_idle_conns: 10
  max_open_conns: 100
  # 连接最大生命周期（分钟）
  conn_max_lifetime: 60
  # 是否启用 SQL 日志
  log_mode: true

# Redis 配置
redis:
  host: localhost
  port: 6379
  password: ""
  # 数据库编号
  db: 0
  # 连接池大小
  pool_size: 10
  # 最小空闲连接数
  min_idle_conns: 5

# RabbitMQ 配置
rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
  vhost: /
  # 交换机配置
  exchange:
    name: microservice_exchange
    type: topic
    durable: true
  # 队列配置
  queues:
    - name: task_queue
      routing_key: task.*
      durable: true
    - name: email_queue
      routing_key: email.*
      durable: true

# AWS S3 配置
aws:
  region: us-east-1
  access_key: your_access_key
  secret_key: your_secret_key
  s3:
    bucket: your-bucket-name
    # 上传文件前缀
    upload_prefix: uploads/
    # 预签名 URL 过期时间（分钟）
    presigned_expire: 60

# 日志配置
logger:
  # 日志级别: debug, info, warn, error
  level: info
  # 日志格式: json, console
  format: json
  # 日志输出路径
  output_paths:
    - stdout
    - logs/app.log
  # 错误日志输出路径
  error_output_paths:
    - stderr
    - logs/error.log
  # 是否启用调用者信息
  enable_caller: true
  # 是否启用堆栈追踪
  enable_stacktrace: true

# 定时任务配置
cron:
  # 是否启用定时任务
  enable: true
  # 任务配置
  jobs:
    # 清理过期数据任务
    - name: clean_expired_data
      spec: "0 0 * * *"  # 每天凌晨执行
      enabled: true
    # 数据统计任务
    - name: daily_statistics
      spec: "0 1 * * *"  # 每天凌晨1点执行
      enabled: true
    # 健康检查任务
    - name: health_check
      spec: "*/5 * * * *"  # 每5分钟执行一次
      enabled: true

# 中间件配置
middleware:
  # CORS 跨域配置
  cors:
    enable: true
    allow_origins:
      - "*"
    allow_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allow_headers:
      - Origin
      - Content-Type
      - Authorization
    expose_headers:
      - Content-Length
    allow_credentials: true
    max_age: 12  # 预检请求缓存时间（小时）
  
  # 请求限流配置
  rate_limit:
    enable: true
    # 每秒最大请求数
    requests_per_second: 100
    # 突发请求数
    burst: 200
  
  # 请求日志配置
  request_log:
    enable: true
    # 是否记录请求体
    log_request_body: false
    # 是否记录响应体
    log_response_body: false

# gRPC 配置
grpc:
  # 最大接收消息大小（MB）
  max_recv_msg_size: 4
  # 最大发送消息大小（MB）
  max_send_msg_size: 4
  # 连接超时时间（秒）
  connection_timeout: 10
  # 保活时间（秒）
  keepalive_time: 30
  # 保活超时时间（秒）
  keepalive_timeout: 10

